### ISSUE TITLE
PAML name collisions

### ISSUE THREAD

**Issue by photocyte** [Bioprotocols/paml#107]
Hi there,

You may have realized, but `PAML` is a widely used package of programs in evolutionary biology. A quick google will turn up the citation, plus the top hits all refer to the same program. It is already referred to in things like Biopython https://biopython.org/wiki/PAML

I would suggest considering an alternative acronym to avoid name collisions. `BAML` (for **bio**protocol), seems to be "available" (but that acronym is also similar to [.bam](https://en.wikipedia.org/wiki/Binary_Alignment_Map) format...)

All the best,
-Tim

**Comment by jakebeal** [comment]
I don't know about others, but I'm certainly receptive to a name change if the community comes up with a good one. I also think we don't need to be in a super rush about it.

**Comment by rpgoldman** [comment]
Other uses of PAML is part of why the python library is "pyPAML" instead of "paml".

The TLAs are all used many times over; perhaps we need to give up on all the four letter abbreviations, as well...

**Comment by photocyte** [comment]
I had a meeting discussing the use of PAML (the other PAML, the one with 10,000 citations) & it reminded me of this issue. These name collisions and/or a strategic rename, is especially relevant with upcoming/ongoing discussions about the future of this PAML. See also: https://github.com/Bioprotocols/container-ontology/issues/33 

What about Laboratory Work Language (LYWL) or Lab Work Language (LWL)?

I'll leave it to folks to determine if there is a coherent pronunciation for those acronyms. My sense is there could be... A quick google of `LWL` or `LYWL` plus `protocol` suggests it is a less-collisiony namespace. `PAML protocol`, at least with my Google, pulls up protocols & related links for the "other PAML" for the 1st page.

It is also relevant as, laboratory work isn't necessarily limited to "biological protocols" (via bioprotocols.org , "Biological Protocols Working Group"), i.e. PAML protocols may include chemistry, or just generic lab manipulations, so "Laboratory language" seems better suited.

**Comment by photocyte** [comment]
Now that PAML governance is setup, wonder if we can revisit? I still think this is a critical issue. Perhaps a two part vote with the community could be done? 
(1) Yes/No on renaming of PAML 
(2) If Yes on (1) succeeds, solicit candidates for rename, and then select via vote

It comes to mind that since there is a `POML` , that a potential rename should also take that into consideration. I.e. `LYWL` would also have `LYOL` , `LabWL` would have `LabOL` , etc.

**Comment by jakebeal** [comment]
I'm fine with a name change, and now's a very good time to do it since we're planning to try to finalize a spec at COMBINE

**Comment by photocyte** [comment]
At the Bioprotocols scrum on 2022-08-30, there was agreement that a rename of `PAML` should be evaluated, and agreement to collect renaming options for evaluation next week. I will also raise this issue onto the Bioprotocols main mailing list. 

A reminder that we have the `bioprotocols.org` name (redirected to `https://bioprotocols.github.io/paml/` & are formally the `Bioprotocols Working Group` . Although the biology focus at the moment, PAML is presumably still suitable for non-biology (i.e. chemistry) or non laboratory or laboratory adjacent (i.e. biological/chemical product manufacturing) contexts, although synthetic biology is likely to be the major first mover for a long time.

Jeremy Cahill suggested "my inner linguist is requesting that we keep disyllabic cvcvc" i.e. like `PAM` - `ML` for PAML

Please post both a longer name & the acronym. Hopefully the acronym pronunciation would be obvious ;) Bonus points if the pronunciation is consistent internationally.

- Laboratory Work Language - LabWL 
- Laboratory Work Language - LWL
- Laboratory Protocol Language - LabPL 
- Laboratory Protocol Language - LPL
- Laboratory Protocol Standard Language - LabPLS
- Scientific Protocol Open Language - SPOL - too similar to SBOL?
- Scientific Protocol Workflow Language - SPWL 

It seems some combination of "laboratory" "biology" "chemistry" "standard" , "protocol" , "scientific" , "workflow" etc. I will plan to evaluate options with Google Searches & present the results before next week.

**Comment by bbartley** [comment]
Hi all, someone else made this point, but I agree with the principle that we should choose a more descriptive name and avoid the alphabet-soup of 4-letter abbreviations, so my preference is leaning toward names that have "Lab" in them

**Comment by danbryce** [comment]
OPR (Open Protocol Representation) is simple and free, pronounced “opper” (rhymes with hopper).

**Comment by markdoerr** [comment]
I like:
Laboratory Protocol Language - LabPL

Other ideas:
sciLang (close to Jake's SciProLang, a little bit shorter)
sciXL - scientific eXpression/eXperiments Language

**Comment by markdoerr** [comment]
I think, it is very important, that the name tells directly the user (not knowing the project), what it is all about.

**Comment by photocyte** [comment]
| Full name      | Acronym | Acronym: # of Google Results | Notes | 
| ----------- | ----------- | ----------- | ----------- |
| Laboratory Work[flow?] Language | LWL       | [10,700,000](https://www.google.com/search?q=%22LWL%22) |
| Laboratory Work[flow?] Language | LabWL        | [16,600](https://www.google.com/search?q=%22LabWL%22) |
| Laboratory Protocol Language | LabPL | [14,600](https://www.google.com/search?q=%22LabPL%22) |
| Laboratory Protocol Standard Language | LabPLS |  [562](https://www.google.com/search?q=%22LabPLS%22) |
| Scientific Protocol Open Language | SPOL | [38,300,000](https://www.google.com/search?q=%22SPOL%22) |
| Scientific Protocol Workflow Language | SPWL | [130,000](https://www.google.com/search?q=%22SPWL%22) |
| Scientific Protocol Modeling Language | SPML | [420,000](https://www.google.com/search?q=%22SPML%22) |
| Laboratory Protocol Language | LabProLan | [0](https://www.google.com/search?q=%22LabProLan%22) |
| ProtocolLanguage | ProtoLang | [5,360](https://www.google.com/search?q=%22ProtoLang%22)  |
| Laboratory Language | LabLang | [9,420](https://www.google.com/search?q=%22LabLang%22) |
| Scientific Protocol Language | SciProLang | [0](https://www.google.com/search?q=SciProLang) |
| Open Protocol Representation | OPR | [28,600,000](https://www.google.com/search?q=OPR) |
| Laboratory Open Protocol Standard | LOPS | [2,430,000](https://www.google.com/search?q=%22LOPS%22) |
| Scientific Open Protocol Standard | SOPS | [14,400,000](https://www.google.com/search?q=%22SOPS%22) |
| Open Protocol | OPro | [2,920,000](https://www.google.com/search?q=%22OPro%22) |
| Scientific Language | sciLang | [2,620](https://www.google.com/search?q=%22SciLang%22)  |
| scientific eXpression/eXpriements Language | sciXL | [14,200](https://www.google.com/search?q=%22sciXL%22) | Trademarked? |

**Comment by jcahill** [comment]
Before I get into a more systematic search later in the day — my first thought in response to Dan's prompt for potentially evocative, non-acronym candidates was along the lines of `mesh ~ distributed network ~ well-connected graph ~ strong but flexible fabric / manifold / weave, plumbing, undergirding`.

- A candidate combining `lab + lattice` comes to mind from there. High frequency term + alliteration and assonance.
- A low frequency counterpart with a similar sense would be `trellis`.

**Comment by gyorgy5635** [comment]
"LabProLan" looks promising.

**Comment by celleleven** [comment]
What about Kinesin(s)?

**Comment by jakebeal** [comment]
To play the "reminiscent but not conflicting" game, one could change it to something like "Qinesin" or "Kynysyn"

**Comment by bbartley** [comment]
@jcahill along those lines, I like LabGraph or GraphProtocolLanguage (although GPL would not be a good abbreviation)

**Comment by photocyte** [comment]
Hi folks, I've updated the table with all the options I've heard. Let me know if I missed something.

Noting: Currently the table only has crude metrics for `google uniqueness` and `conflicts with preexisting projects in the science and/or software` domains, I wouldn't lean too much on an especially low or especially high number? There are other axes to be considered, i.e. is it evocative (https://github.com/Bioprotocols/paml/issues/107#issuecomment-1238409837), is it easy to remember, is it easy to pronounce (internationally), is it self-descriptive (https://github.com/Bioprotocols/paml/issues/107#issuecomment-1237902753), is it an acronym vs single word, vs multi word (https://github.com/Bioprotocols/paml/issues/107#issuecomment-1231897243)?

My personal preference is Laboratory Open Protocol - `LabOPro` - `LabOP` . Although quite similar to `labops` , `labop` is suprisingly unencumbered, and could have some fun mnemonic type mechanisms "Research is tough, but before you need to get your labops figured out, first try LabOP. It'll make it easier" 

For `Graph` I think in a biological user context, that has a negative weight in the `self-descriptive` axis, i.e. a biological user would think of a graph as in an excel graph, rather than a protocol graph (most "protocols" in their experience are linear sequences)

**Comment by rpgoldman** [comment]
> To play the "reminiscent but not conflicting" game, one could change it to something like "Qinesin" or "Kynysyn"

I would prefer that we not end up with one of those names that doesn't give any hint of what the thing actually is.  This sounds like the name of a sedan! ;-)

**Comment by rpgoldman** [comment]
> For `Graph` I think in a biological user context, that has a negative weight in the `self-descriptive` axis, i.e. a biological user would think of a graph as in an excel graph, rather than a protocol graph (most "protocols" in their experience are linear sequences)

+1 to this. There is already too much ambiguity in the meanings of graph. I think of graph as "directed graph," but that's because I have a computer science background.

**Comment by rpgoldman** [comment]
> My personal preference is Laboratory Open Protocol - `LabOPro` - `LabOP` . Although quite similar to `labops` , `labop` is suprisingly unencumbered, and could have some fun mnemonic type mechanisms "Research is tough, but before you need to get your labops figured out, first try LabOP. It'll make it easier"

I like this, but I would prefer we expand the "O" to something like "OpenLabPro". 

"Pro" doesn't seem great, though, because it prefixes too many different words.  "Proto" is not really better, because it could be "Prototype."  Maybe we should just suck it up and go for "OpenLabProtocol".

Or maybe this is a *reductio ad absurdum* and we should just stick to PAML?

**Comment by rpgoldman** [comment]
> I like: Laboratory Protocol Language - LabPL

+1

> Other ideas: sciLang (close to Jake's SciProLang, a little bit shorter) sciXL - scientific eXpression/eXperiments Language

"sci" is too unspecific, IMO.  Compare with "scipy" for example.

**Comment by danbryce** [comment]
labop.io and labops.io are available. I vote for either of those.  Unlike some of the others, these are easy to pronounce and are descriptive.

**Comment by photocyte** [comment]
I'd like to suggest from Dan's post onwards (https://github.com/Bioprotocols/paml/issues/107#issuecomment-1242283465) we start voting on options - please make another post if you'd like to throw a particular option into the ring? I'll make a post for PAML itself. I'd like to suggest we follow ranked choice voting (https://en.wikipedia.org/wiki/Ranked_voting), so please react to options with your first preference, 2nd preference, 3rd preference. Too bad Github doesn't support the 1️⃣ , 2️⃣ reactions on posts. So, let's use ❤️ as first choice, 👍 as second choice, 🚀 as 3rd choice, 🎉 as 4th choice.

**Comment by photocyte** [comment]
Leave reactions here for your votes for PAML

**Comment by rpgoldman** [comment]
> I'd like to suggest from Dan's post onwards ([#107 (comment)](https://github.com/Bioprotocols/paml/issues/107#issuecomment-1242283465)) we start voting on options - please make another post if you'd like to throw a particular option into the ring? I'll make a post for PAML itself. I'd like to suggest we follow ranked choice voting ([en.wikipedia.org/wiki/Ranked_voting](https://en.wikipedia.org/wiki/Ranked_voting)), so please react to options with your first preference, 2nd preference, 3rd preference. Too bad Github doesn't support the 1️⃣ , 2️⃣ reactions on posts. So, let's use ❤️ as first choice, 👍 as second choice, 🚀 as 3rd choice, 🎉 as 4th choice.

We don't necessarily have only one comment per post. So maybe better to do a two phase:

1. Pick an arbitrary deadline (say midnight anywhere on the globe today or Saturday)
2. Harvest candidate names and put them on a Google sheet
3. Set another deadline, and collect votes
4. Execute the ranked choice process

And, to continue my pedantry, it's instant runoff you propose as our method of ranked choice voting, correct? That would be fine with me.

**Comment by photocyte** [comment]
Will have to read up on instant runoff though I assume the answer is "yes" (I just know ranked choice is "good" although I haven't tried to administer such an election). I'm just all for whichever has the least amount of extra work & keeps the current state in a single place - the reactions on particular `posts` seemed to accomplish that, Google sheets seems like extra work, unless we prefer this election to be closed to Bioprotocols google group members. I agree, the deadline shouldn't be "today" it is already evening time in Europe, but didn't want to suggest a particular deadline!

**Comment by rpgoldman** [comment]
> edit: `We don't necessarily have only one comment per post. ` Yes, but can rely on folks to police their own reactions to ensure they're not voting ❤️ ❤️ ❤️ on every option?

Isn't the problem that we need to have one post (comment) per candidate?  That would give us a lot of posting and scrolling. That's why I thought the google sheet would be a better choice.  I suppose we could have a markdown table instead, if anyone was feeling particularly masochistic!

**Comment by photocyte** [comment]
I don't expect there to be more than 4 candidates, so didn't feel like it would be too many posts. I'm used to a lot of scrolling I guess ;)  But am open to alternatives. Just didn't want to leave things in an ambiguous state vs taking the initiative to have a vote "now".

**Comment by danbryce** [comment]
Poll is live at: https://github.com/Bioprotocols/paml/discussions/161

**Comment by photocyte** [comment]
Aforementioned poll completed with `LabOP` coming in first. LabOP was discussed and agreed upon at the 2022-09-20 weekly PAML meeting (minutes here:https://docs.google.com/document/d/185LQx4wsPT2rZUr_UnlRTaeKBBojFkWGfByHHN12p34/edit#heading=h.47fz4ugx1qlx) . Therefore, closing this thread given the agreement on LabOP.
