### ISSUE TITLE
Add support for NCBI,NCIT,SBO, and SO Ontologies

### ISSUE THREAD

**Issue by palibhasataolamang** [Bioprotocols/paml#109]
Add ontology resolution for NCBI,NCIT,SBO, and SO ontologies. Some users might want to use native terms from those ontologies that are not in OM.

For example: transfer = protocol.primitive_step('TransferInto', source=transfer_org.output_pin('samples'), destination=transfer_dest.output_pin('samples'), amount=sbol3.Measure(10, tyto.OM.microliter), dispenseVelocity=sbol3.Measure(0.3,tyto.NCIT.milliliter_per_second), mixCycles=sbol3.Measure(7,tyto.NCIT.count))

dispenseVelocity and mixCycles fail to resolve into units in the output pdf. See attached PDF.

[test.pdf](https://github.com/Bioprotocols/paml/files/8020772/test.pdf)

**Comment by palibhasataolamang** [comment]
I was actually also wondering how machine support and conversion would be done if other ontologies were supported. But you're right. If its difficult to maintain and support less organized ontologies it's better to leave them out at this stage.

But in the above example, how should UnitDivision be used since Measure expects a URI for the units part?

**Comment by jakebeal** [comment]
When you create the UnitDivision object, it will have an identity URI and can be added to the PAML document. Its URI would then be the URI given for the unit.

**Comment by palibhasataolamang** [comment]
Gotcha. Thanks!
