### ISSUE TITLE
Commitment to RDF?

### ISSUE THREAD

**Issue by jakebeal** [Bioprotocols/paml#11]
Use of RDF has both upsides and downsides.

Some key upsides:
 - Universal graph representation
 - Not tied to any programming language: most languages have good RDF libraries
 - Extensible for custom uses
 - Readily integrated with existing biomedical ontologies (e.g., SO, SBO, GO) and databases (e.g., CHEBI, UniProt, PubChem).
 - Not tied to a specific serialization format.

SBOL's RDF approach also adds the following:
 - Scoping and document structure rules
 - Strong inference rules

Downsides:
 - Triple-based representation is less efficient for lists
 - Bad odor from association with OWL

We should have a discussion of upsides versus downsides and potential alternatives in order to reach consensus on whether to commit to RDF or use an alternative instead.

**Comment by bjkeller** [comment]
What we are describing is analogous to an abstract syntax tree of a programming language, which is an internal representation that wouldn't ordinarily be shared.
Using RDF implies that we are sharing this representation, but the basic question is whether this makes sense or should we look for a a simplified representation that could be used?

**Comment by jakebeal** [comment]
I'm not sure that analogy holds. 

RDF comes with a set of semantics for how to manage certain aspects of scoping and composition. These can be strengthened to allow more computations (like we've done in SBOL), but they cannot be weakened. Thus, for example, if we use RDF it means that you have to think about how you're going to manage deconfliction with other people's separately defined protocols up front, rather than leaving collisions to be discovered dynamically.

**Comment by bjkeller** [comment]
Well, if it doesn't hold, we aren't talking about the same thing

**Comment by jakebeal** [comment]
Consensus decision at 5/17 protocols retreat: we will use RDF with SBOL closures.
This decision will be subject to review and discussion later. Some significant reservations remain, notably:
- Implications of the requirement of using IRIs
- Potential for interaction with RDF/OWL tooling that is not closure-aware

Based on the discussion, I have also opened an issue for allowing a default namespace again in pySBOL3: https://github.com/SynBioDex/pySBOL3/issues/254, reversing the prior decision to remove this (https://github.com/SynBioDex/pySBOL3/issues/99)

**Comment by jakebeal** [comment]
This was long ago decided.
