### ISSUE TITLE
PAML landing page?

### ISSUE THREAD

**Issue by photocyte** [Bioprotocols/paml#143]
Would an overall project landing page (i.e. a [https://bioprotocols.github.io/](https://bioprotocols.github.io/) Github page?), be worthwhile?

It could be a single point to point people to the Google Group, Slack, Github, etc.

It could also puts PAML in an introductory context, both for software people (developers) and users (biologists/chemists/lab workers). I.e., have as many related projects (Nextflow, Camunda/BPMN, etc.) mentioned to boost search engine discoverability?

**Comment by photocyte** [comment]
I'm only familiar with Github Pages, which at least in my experience using something like Jekyll & existing templates was pretty straightforward (https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll ; https://github.com/hydecorp/hydejack) . I think just a 1-page, here is a pointer + some figures of the current PAML resources would be the way to go.

**Comment by jakebeal** [comment]
Good idea; I've invited you for additional rights on the organization so that you can set this up if you are able!

**Comment by photocyte** [comment]
I have made a page which is now live at https://github.com/Bioprotocols . Please feel free to change as desired. I'll leave this issue open as perhaps it touches on a broader question of documentation?

The `.github` special repository also enables a few other things relevant to governance:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by jakebeal** [comment]
I'm going to close this issue, since I think this is a good minimal implementation of a solution, and upgrades can be added as their own issues as you or others are motivated to think of specifics.

If you want to set up a pull request with the governance files, that seems it would be a good place to start some of the simpler discussions there as well.
