### ISSUE TITLE
Alex Casas reports that `pip install paml` won't work

### ISSUE THREAD

**Issue by rpgoldman** [Bioprotocols/paml#66]
PyPi already has a different library named paml: https://pypi.org/project/paml/

**Comment by rpgoldman** [comment]
Is there some way we can grab up a different name that is in the same family? We have SBOL, PAML, OPIL, and POML, and there’s SBML, etc.  Suddenly switching to a real word might be confusing.

If you are ok with limiting to *BIO* protocols, what about just changing to “BPAML” or “BPML”?  “BPAML” is free on PyPi. I’m not as sure about BPML.  I get search hits for that, but not an actual library named “BPML”.

I’m ok with whatever people like, just wanted to offer another option.

**Comment by danbryce** [comment]
Sorry BAM is taken. BAML is open on pypi. 

Dan

**Comment by jakebeal** [comment]
We need to actually make a decision and push this out. 
Suggestion: libpaml ?

**Comment by rpgoldman** [comment]
I'm a little worried that that sounds like some kind of Linux binary library, rather than being Python-ish.

pyPAML ?

**Comment by jakebeal** [comment]
I like pyPAML.

**Comment by vignoni** [comment]
I like pyPAML also!

**Comment by jakebeal** [comment]
That's curious... on my machine it runs through just fine... clearly a tarball on github isn't a good way to do that distribution, though. @rpgoldman : can you publish a version of the container ontology to pypi?

**Comment by rpgoldman** [comment]
> @rpgoldman : can you publish a version of the container ontology to pypi?

To be honest, I don't know -- I have never tried.  Could someone point me at a tutorial?

Also, we should probably be more careful in general about distinguishing test dependencies from library dependencies.

**Comment by jakebeal** [comment]
https://pythonpackaging.info/07-Package-Release.html

**Comment by tsdobbs** [comment]
Seems to be working for me now

Both `pip install paml` and `pip3 install git+https://github.com/Bioprotocols/paml.git --no-cache-dir`

**Comment by tsdobbs** [comment]
> I like pyPAML.

I like pyPAML as well, on pypi, and PAML for the general language.

**Comment by jcahill** [comment]
pyPAML looks perfectly acceptable.
