### ISSUE TITLE
PAML needs a license

### ISSUE THREAD

**Issue by jakebeal** [Bioprotocols/paml#71]
How do we not have a license on the PAML repository yet?

I would suggest that we use a standard permissive open license.  SBOL_factory, SBOL-utilities, and pySBOL3 are all using the MIT License for code, so I would suggest we do so here as well.  Likewise, we are using CC-BY for the specification, and so can use that for non-code material here as well.

@bbartley @danbryce @rpgoldman : please either affirm your agreement to the MIT License / CC-BY or suggest a reason why we should use something else. Once the four of us have affirmed, that is all of the GitHub-recognized contributors, and we can add it to the repository.

**Comment by rpgoldman** [comment]
I like the CC license for the standard.  Any reason we couldn't insist on attribution for the code, as well, and just use CC-BY for everything?

**Comment by rpgoldman** [comment]
Sounds like MIT it is, then.
