### ISSUE TITLE
RDFLIB requirement inconsistent with SBOL Factory

### ISSUE THREAD

**Issue by rpgoldman** [Bioprotocols/paml#78]
We require RDFLIB 5, and SBOL Factory requires 6, which is why our GitHub CI actions are broken.

I don't know why RDFLIB is pinned to 5, I'm afraid.

**Comment by bbartley** [comment]
I think rdflib 6 is now required by pySBOL, hence is also a requirement for sbol_factory, so we will have to upgrade paml's dependency, too.
