### ISSUE TITLE
Issue with paml-check dependency

### ISSUE THREAD

**Issue by rpgoldman** [Bioprotocols/paml#81]
I am trying to reinstall PAML in order to fix dependency issues.

I'm finding that installing paml-check is very difficult, because it pulls in `z3-solver`, which looks like it's building a copy of Z3.

I grepped for `paml_check` in python files in the paml library, and I don't see anything.

So I wonder if `paml-check` could be made into some kind of optional dependency.

**Comment by bbartley** [comment]
I also encountered this problem -- it prevents me from installing paml locally on my machine.  PR #85 moves `paml-check` to an optional dependency, but I don't know if that's the right solution.  @danbryce can you please review the PR and let us know if this is acceptable? 

It looks like `paml_check` was previously used in this test file, but it is currently commented out: https://github.com/Bioprotocols/paml/blob/main/test/test_time.py

**Comment by danbryce** [comment]
I reviewed and approved it. :)
