### ISSUE TITLE
Can't deploy wheel via PyPI because of git dependencies

### ISSUE THREAD

**Issue by bbartley** [Bioprotocols/paml#91]
Uploading a wheel to PyPI results in:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: 'container-ontology @ https://github.com/rpgoldman/container-ontology/tarball/main'
```
I'm not sure if there is an alternative way to configure the `setup.py` script that will allow git repos as dependencies, or if we should just move the container contology to a git submodule.

**Comment by jakebeal** [comment]
For now, let's start with it as a git submodule in order to enable a working release.

Ultimately, however, I think we need to publish the container ontology and obtain it either as a package or from an ontology server.

**Comment by rpgoldman** [comment]
Do you know what the container-ontology dependency is?  I can get the container ontology moved and ready for pypi next week. Wondering if it would be just as easy to make it not be a dependency until that happens.

It’s an ontology, anyway, so I think you would just be getting URIs, not code. I’ll take a peek.

**Comment by rpgoldman** [comment]
I just checked, and while the container-ontology’s URI is referenced, I don’t see any code dependency. So probably we could just drop the dependency for now.

**Comment by jakebeal** [comment]
Plan is to deploy with the dependency cut for now and the test that uses the container-ontology marked as known failing. When @rpgoldman deploys container ontology on pypi, we will then recover the test.
